system:
  interface: null
  csv_output_path: null
  test_mode_output_path: null
  log_file_path: null
  google_drive_upload: false
  google_drive_folder_id: null
  token_file_path: null
  csv_rotation_rows: 1000000

model:
  batch_size: 1000

mitigation:
  enable_blocking: false
  block_duration_seconds: 180
  admin_email: ""
  smtp_server: ""
  smtp_port: 587
  smtp_user: ""
  smtp_password: ""
