/var/log/ddos-martummai/*.log {
    daily
    rotate 90
    missingok
    notifempty
    compress
    delaycompress

    dateext
    dateformat -%Y-%m-%d

    create 0640 root root
    sharedscripts
}